### ISSUE TITLE
After using the .setValues()method, it cannot be executed immediately

### ISSUE THREAD

**Issue by Ch-Shi** [romellem/impulsion#22]
After using the .setValues ​​(<number>, <number>, <number | null>, <number | null>) method, it cannot be executed immediately. It needs to be touched once to execute.

**Comment by romellem** [comment]
I think I understand what you mean. I made a [quick demo](https://codepen.io/romellem/pen/vYNprXg), and if I drag the dot, set the `x` and `y` values to 0, the dot doesn't move. It only moves to the upper corner once I start dragging again.

Would adding a new API to manually trigger our `onUpdate` callback work here? Similar to when a [new instance initializes with initial values passed on](https://github.com/romellem/impulsion/blob/e64821b1/src/impulsion.js#L104).

For example, if I added a `.update()` function that just looked like this:

```js
this.update = function() {
  callUpdateCallback();
}
```

Then you could do this:

```js
myThing.setValues(x, y, px, py);
myThing.update();
```

**Comment by Ch-Shi** [comment]
Thank you very much for your answer, I will try your method. I must admit that I am still a newbie in programming☺

**Comment by romellem** [comment]
@Ch-Shi I made a quick update in v1.1.0, you can now run `.forceUpdate()` to call the `onUpdate()` function.

I updated the [same codepen from before](https://codepen.io/romellem/pen/vYNprXg) to show its usage.

```js
var myThing = new Impulsion({ ... });

// Call `.forceUpdate()` after running `.setValues()` to immediately update the scene
myThing.setValues(...);
myThing.forceUpdate();
```
