### ISSUE TITLE
Request has been deprecated. 

### ISSUE THREAD

**Issue by NotMoni** [romellem/impulsion#8]
Hey,

It looks like you use the request package in your code.
Request has been deprecated. 
Request package is unmaintained and will no longer be updated by the publisher.
You should switch to another HTTP request library for Node.js

Some other Library:
[Node-fetch](https://www.npmjs.com/package/node-fetch)
[Got](https://www.npmjs.com/package/got)
[Axios](https://www.npmjs.com/package/axios)

**Comment by romellem** [comment]
I think this was when I used Parcel, but I switched to Rollup in #11, so I no longer use that dep.

**Comment by NotMoni** [comment]
Ok, cool.
 :D
